### ISSUE TITLE
can't support TortoiseSVN 1.11.0 @ v0.7.1

### ISSUE THREAD

**Issue by zerocraft** [Revenge282/StatSVN#1]
can't support TortoiseSVN 1.11.0 @ v0.7.1

**Comment by AusHick** [comment]
There doesn't seem to be any issues generating under the setup here.  I'm assuming you're getting errors related to not having SVN tools on your environment path.  When you go to install TortoiseSVN, did you enable the command-line tools?

Here:
https://puu.sh/CnbOI/93fa19f99b.png

If not, you can enable them by running the TortoiseSVN installer again, click Modify, and selecting that option.  Otherwise, I am going to need more details.

Let me know how that works.

**Comment by zerocraft** [comment]
I think it may be a file coding problem. I have files named by Chinese.
Don't worry about it. Thank you for your tools.
